### ISSUE TITLE
How to mute/unmute across different apps in Windows?

### ISSUE THREAD

**Issue by shonilchi** [DelPyth/ahk-trix#1]
I tried using the AHK script from https://www.autohotkey.com/boards/viewtopic.php?t=15509, where I tried to get the IDs and run it.. it works in terms of turning off the 'sound' and not the microphone.

Also, I am using MS Teams and Skype in my system and I need one AHK hotkey to mute/unmute on both of these. How do I achieve this? Could you please help?

**Comment by DelPyth** [comment]
This isn't quite the right place to ask for help with AHK scripts. This repository is used for general tricks and tips across AHK. It's recommended to look at the forums and ask for help here: https://www.autohotkey.com/boards/viewforum.php?f=76
